export const BookingsActions = {
  SET_BOOKING_SLOTS: 'SET_BOOKING_SLOTS',
  SET_LOADING_BOOKINGS_SLOTS: 'SET_LOADING_BOOKINGS_SLOTS',
  RESET_LOADING_BOOKINGS_SLOTS: 'RESET_LOADING_BOOKINGS_SLOTS',
  USER_DEPARTMENTS: 'USER_DEPARTMENTS',
  SET_LOADING_BOOK_APPOINTMENT: 'SET_LOADING_BOOK_APPOINTMENT',
  SET_APPOINTMENTS: 'SET_APPOINTMENTS',
  SET_LOADING_APPOINTMENTS:'SET_LOADING_APPOINTMENTS',
  RESET_BOOKINGSSTATE: 'RESET_BOOKINGSSTATE',
};
