export const DoctorActions = {
  GET_DOCTORS: 'GET_DOCTORS',
  SET_LOADING_DOCTORS: 'SET_LOADING_DOCTORS',
  GET_DOCTOR_DETAILS: 'GET_DOCTOR_DETAILS',
  SET_LOADING_DOCTOR_DETAILS: 'SET_LOADING_DOCTOR_DETAILS',
  GET_DOCTOR_REVIEWS: 'GET_DOCTOR_REVIEWS',
  SET_LOADING_DOCTOR_REVIEWS: 'SET_LOADING_DOCTOR_REVIEWS',
  RESET_DOCTOR_DETAILS: 'RESET_DOCTOR_DETAILS',
  RESET_DOCTOR_STATE: 'RESET_DOCTOR_STATE',
  SET_POSTING_REVIEW: 'SET_POSTING_REVIEW',
};
